# Generated by Django 2.2.6 on 2019-11-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.CharField(default='', editable=False, max_length=80),
        ),
    ]
